name: Just run
on: workflow_dispatch
jobs:
  run-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run script with env
        run: python3 script.py
        env:
          GREETING_MESSAGE: "Witaj z poziomu GitHub Actions!"
